### ISSUE TITLE
GOLD grammar - different Alternative notation

### ISSUE THREAD

**Issue by tf3pm** [picoe/Eto.Parse#35]
Hi all, could you please help me?
I have GOLDparser grammar:

`            const string testedGrammer = @"
""Case Sensitive"" = False
""Start Symbol""   = <Program>

Identifier          = ({Letter}?|{Digit}+)

<Program> ::= <VariableExpression>

<VariableExpression> ::= Identifier
";
`

this input does not match the grammar:

`            const string expression03 = @"45646";`

But if I change the notation for the Identifier to:

`Identifier          = ({Digit}+|{Letter}?)`

everything works well.

Could you please help me?

Thanks,
Tomas

**Comment by cwensley** [comment]
Hi Tomas,

Thanks for submitting the issue, but this is a side-effect of using a recursive descent parser vs. a state parser.

In Eto.Parse, the first alternative `{Letter}?` will always match and will not try the second alternative, even if it is "more valid".  This means the order of the alternatives matter in Eto.Parse, even when using other grammars. 

In more detail, `{Letter}?` basically means, if the current character is a letter, it is a match, otherwise it is still a match with a zero-length.

Hope this helps!
Curtis.

**Comment by tf3pm** [comment]
Thanks, Curtis!
